// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate-imagename-constants.sh. DO NOT EDIT.

package imagevector

const (
	// ImageNameUagentUsandbox is a constant for an image in the image vector with name 'agent-sandbox'.
	ImageNameUagentUsandbox = "agent-sandbox"
)
